#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliminatoriasLinqASPNET_EdgarDuarte_1193520.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="partidoDB")]
	public partial class PartidoDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertdetalle(detalle instance);
    partial void Updatedetalle(detalle instance);
    partial void Deletedetalle(detalle instance);
    partial void Insertequipo(equipo instance);
    partial void Updateequipo(equipo instance);
    partial void Deleteequipo(equipo instance);
    partial void Insertfecha(fecha instance);
    partial void Updatefecha(fecha instance);
    partial void Deletefecha(fecha instance);
    #endregion
		
		public PartidoDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["partidoDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<detalle> detalle
		{
			get
			{
				return this.GetTable<detalle>();
			}
		}
		
		public System.Data.Linq.Table<equipo> equipo
		{
			get
			{
				return this.GetTable<equipo>();
			}
		}
		
		public System.Data.Linq.Table<fecha> fecha
		{
			get
			{
				return this.GetTable<fecha>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RegistroDetalleFecha")]
		public int RegistroDetalleFecha([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codequipo1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codequipo2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gol1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gol2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, codequipo1, codequipo2, gol1, gol2);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle")]
	public partial class detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _fkIdFecha;
		
		private System.Nullable<int> _goles1;
		
		private System.Nullable<int> _goles2;
		
		private EntityRef<fecha> _fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfkIdFechaChanging(System.Nullable<int> value);
    partial void OnfkIdFechaChanged();
    partial void Ongoles1Changing(System.Nullable<int> value);
    partial void Ongoles1Changed();
    partial void Ongoles2Changing(System.Nullable<int> value);
    partial void Ongoles2Changed();
    #endregion
		
		public detalle()
		{
			this._fecha = default(EntityRef<fecha>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkIdFecha", DbType="Int")]
		public System.Nullable<int> fkIdFecha
		{
			get
			{
				return this._fkIdFecha;
			}
			set
			{
				if ((this._fkIdFecha != value))
				{
					if (this._fecha.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkIdFechaChanging(value);
					this.SendPropertyChanging();
					this._fkIdFecha = value;
					this.SendPropertyChanged("fkIdFecha");
					this.OnfkIdFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goles1", DbType="Int")]
		public System.Nullable<int> goles1
		{
			get
			{
				return this._goles1;
			}
			set
			{
				if ((this._goles1 != value))
				{
					this.Ongoles1Changing(value);
					this.SendPropertyChanging();
					this._goles1 = value;
					this.SendPropertyChanged("goles1");
					this.Ongoles1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goles2", DbType="Int")]
		public System.Nullable<int> goles2
		{
			get
			{
				return this._goles2;
			}
			set
			{
				if ((this._goles2 != value))
				{
					this.Ongoles2Changing(value);
					this.SendPropertyChanging();
					this._goles2 = value;
					this.SendPropertyChanged("goles2");
					this.Ongoles2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fecha_detalle", Storage="_fecha", ThisKey="fkIdFecha", OtherKey="id", IsForeignKey=true)]
		public fecha fecha
		{
			get
			{
				return this._fecha.Entity;
			}
			set
			{
				fecha previousValue = this._fecha.Entity;
				if (((previousValue != value) 
							|| (this._fecha.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fecha.Entity = null;
						previousValue.detalle.Remove(this);
					}
					this._fecha.Entity = value;
					if ((value != null))
					{
						value.detalle.Add(this);
						this._fkIdFecha = value.id;
					}
					else
					{
						this._fkIdFecha = default(Nullable<int>);
					}
					this.SendPropertyChanged("fecha");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.equipo")]
	public partial class equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _puntos;
		
		private EntitySet<fecha> _fecha;
		
		private EntitySet<fecha> _fecha1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnpuntosChanging(System.Nullable<int> value);
    partial void OnpuntosChanged();
    #endregion
		
		public equipo()
		{
			this._fecha = new EntitySet<fecha>(new Action<fecha>(this.attach_fecha), new Action<fecha>(this.detach_fecha));
			this._fecha1 = new EntitySet<fecha>(new Action<fecha>(this.attach_fecha1), new Action<fecha>(this.detach_fecha1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Int")]
		public System.Nullable<int> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="equipo_fecha", Storage="_fecha", ThisKey="id", OtherKey="fkIdE1")]
		public EntitySet<fecha> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="equipo_fecha1", Storage="_fecha1", ThisKey="id", OtherKey="fkIdE2")]
		public EntitySet<fecha> fecha1
		{
			get
			{
				return this._fecha1;
			}
			set
			{
				this._fecha1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_fecha(fecha entity)
		{
			this.SendPropertyChanging();
			entity.equipo = this;
		}
		
		private void detach_fecha(fecha entity)
		{
			this.SendPropertyChanging();
			entity.equipo = null;
		}
		
		private void attach_fecha1(fecha entity)
		{
			this.SendPropertyChanging();
			entity.equipo1 = this;
		}
		
		private void detach_fecha1(fecha entity)
		{
			this.SendPropertyChanging();
			entity.equipo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fecha")]
	public partial class fecha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _fecha1;
		
		private System.Nullable<int> _fkIdE1;
		
		private System.Nullable<int> _fkIdE2;
		
		private EntitySet<detalle> _detalle;
		
		private EntityRef<equipo> _equipo;
		
		private EntityRef<equipo> _equipo1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfecha1Changing(System.Nullable<System.DateTime> value);
    partial void Onfecha1Changed();
    partial void OnfkIdE1Changing(System.Nullable<int> value);
    partial void OnfkIdE1Changed();
    partial void OnfkIdE2Changing(System.Nullable<int> value);
    partial void OnfkIdE2Changed();
    #endregion
		
		public fecha()
		{
			this._detalle = new EntitySet<detalle>(new Action<detalle>(this.attach_detalle), new Action<detalle>(this.detach_detalle));
			this._equipo = default(EntityRef<equipo>);
			this._equipo1 = default(EntityRef<equipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fecha", Storage="_fecha1", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha1
		{
			get
			{
				return this._fecha1;
			}
			set
			{
				if ((this._fecha1 != value))
				{
					this.Onfecha1Changing(value);
					this.SendPropertyChanging();
					this._fecha1 = value;
					this.SendPropertyChanged("fecha1");
					this.Onfecha1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkIdE1", DbType="Int")]
		public System.Nullable<int> fkIdE1
		{
			get
			{
				return this._fkIdE1;
			}
			set
			{
				if ((this._fkIdE1 != value))
				{
					if (this._equipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkIdE1Changing(value);
					this.SendPropertyChanging();
					this._fkIdE1 = value;
					this.SendPropertyChanged("fkIdE1");
					this.OnfkIdE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkIdE2", DbType="Int")]
		public System.Nullable<int> fkIdE2
		{
			get
			{
				return this._fkIdE2;
			}
			set
			{
				if ((this._fkIdE2 != value))
				{
					if (this._equipo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkIdE2Changing(value);
					this.SendPropertyChanging();
					this._fkIdE2 = value;
					this.SendPropertyChanged("fkIdE2");
					this.OnfkIdE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fecha_detalle", Storage="_detalle", ThisKey="id", OtherKey="fkIdFecha")]
		public EntitySet<detalle> detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				this._detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="equipo_fecha", Storage="_equipo", ThisKey="fkIdE1", OtherKey="id", IsForeignKey=true)]
		public equipo equipo
		{
			get
			{
				return this._equipo.Entity;
			}
			set
			{
				equipo previousValue = this._equipo.Entity;
				if (((previousValue != value) 
							|| (this._equipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._equipo.Entity = null;
						previousValue.fecha.Remove(this);
					}
					this._equipo.Entity = value;
					if ((value != null))
					{
						value.fecha.Add(this);
						this._fkIdE1 = value.id;
					}
					else
					{
						this._fkIdE1 = default(Nullable<int>);
					}
					this.SendPropertyChanged("equipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="equipo_fecha1", Storage="_equipo1", ThisKey="fkIdE2", OtherKey="id", IsForeignKey=true)]
		public equipo equipo1
		{
			get
			{
				return this._equipo1.Entity;
			}
			set
			{
				equipo previousValue = this._equipo1.Entity;
				if (((previousValue != value) 
							|| (this._equipo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._equipo1.Entity = null;
						previousValue.fecha1.Remove(this);
					}
					this._equipo1.Entity = value;
					if ((value != null))
					{
						value.fecha1.Add(this);
						this._fkIdE2 = value.id;
					}
					else
					{
						this._fkIdE2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("equipo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle(detalle entity)
		{
			this.SendPropertyChanging();
			entity.fecha = this;
		}
		
		private void detach_detalle(detalle entity)
		{
			this.SendPropertyChanging();
			entity.fecha = null;
		}
	}
}
#pragma warning restore 1591
